"""Add drivers column to Post model

Revision ID: 5cd832bfbea7
Revises: e7d9cfb7d146
Create Date: 2025-08-02 19:25:57.618751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd832bfbea7'
down_revision = 'e7d9cfb7d146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drivers', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('drivers')

    # ### end Alembic commands ###
