"""Add ward column to Post model

Revision ID: b8b7c7341e42
Revises: 5cd832bfbea7
Create Date: 2025-08-02 20:18:56.382116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b7c7341e42'
down_revision = '5cd832bfbea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ward', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('ward')

    # ### end Alembic commands ###
